# Generated by Django 5.0.4 on 2026-02-22 23:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or Mapbox icon name, e.g. '🎉' or 'music'", max_length=50
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for map pin, e.g. #FF5733",
                        max_length=7,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("organizer_name", models.CharField(max_length=150)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Event pin location (lng, lat)", srid=4326
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("neighborhood", models.CharField(blank=True, default="", max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("is_free", models.BooleanField(default=True)),
                ("price_info", models.CharField(blank=True, max_length=200, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("ticket_url", models.URLField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="events/covers/%Y/%m/"),
                ),
                ("max_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True,
                        help_text="iCal RRULE string, e.g. FREQ=WEEKLY;BYDAY=SA",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, help_text="Verified by admin")),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="events.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="cities.city",
                    ),
                ),
                (
                    "organizer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="events", to="events.tag"),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full JSON snapshot of event fields at time of edit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event History",
                "verbose_name_plural": "Event Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("INTERESTED", "Interested"),
                            ("GOING", "Going"),
                            ("SAVED", "Saved"),
                            ("REPORTED", "Reported"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Interaction",
                "verbose_name_plural": "Event Interactions",
                "ordering": ["-created_at"],
                "unique_together": {("user", "event", "interaction_type")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_datetime"], name="events_even_status_02a0ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city", "status"], name="events_even_city_id_1cce9b_idx"),
        ),
    ]
