# Generated by Django 5.0.4 on 2026-02-22 23:08

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("state", models.CharField(help_text="State abbreviation, e.g. RS", max_length=2)),
                ("country", models.CharField(default="BR", max_length=2)),
                (
                    "bounding_box",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Polygon defining the valid area for event pins in this city.",
                        srid=4326,
                    ),
                ),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Map center point (lat/lng) displayed when browsing this city.",
                        srid=4326,
                    ),
                ),
                ("zoom_default", models.FloatField(default=13.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
    ]
